### ISSUE TITLE
Is there any event for drop over on file-drop?

### ISSUE THREAD

**Issue by eliezerreis** [jkuri/ng2-uploader#20]
It's nice to change the color of drop area, for example.

**Comment by jkuri** [comment]
You can set any style you want to you drop area with CSS.

**Comment by leocaseiro** [comment]
Example with drop-over effect:

```javascript
<div
        class="drop-zone"
        (dragenter)="isOver = true"
        (dragover)="isOver = true"
        (dragleave)="isOver = false"
        [ngClass]="{'on-drop-over': isOver}"
        [ng-file-drop]="options">
        Drop here
</div>
```

```css
.drop-zone {
    height: 200px;
    width: 80%
}
.on-drop-over {
    background-color: grey;
}
```
